steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/dummy-repo/cloud-run-demo', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/dummy-repo/cloud-run-demo']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - cloud-run-demo
      - --image=us-central1-docker.pkg.dev/$PROJECT_ID/dummy-repo/cloud-run-demo
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/dummy-repo/cloud-run-demo

options:
  logging: CLOUD_LOGGING_ONLY
